services:
  - type: web
    name: pdf-extracter
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "chainlit run app.py --host 0.0.0.0 --port ${PORT}"
    envVars:
      - key: MISTRAL_API_KEY
        sync: false